<a href="https://colab.research.google.com/github/AtharvaDalvi2703/ML_NLP_worksheet1/blob/main/ML_worksheet1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1


In [ ]:
import numpy as np
arr= np.random.randint(1,51,size=(5,4))
newarr=np.array([])#extracted elements
col=len(arr[0])-1
row=len(arr)
print(arr)

for x in  range(0,row):
  newarr=np.append(newarr,arr[x][col])#antidiagonal
  col-=1
  if col<0:
    break

for x in range(0,len(arr)):
  print(np.max(arr[x]),end=" ")

Mean=np.mean(arr)
less=arr<=Mean
less_than=arr[less] #less than or equal to
print("\n",less_than)

def numpy_boundry_traversal(matrix):
    temp = matrix.copy()
    spiral  = []

    while temp.size:
        spiral.extend(temp[0].tolist())
        temp = temp[1:]
        if temp.size == 0: break


        spiral.extend(temp[:, -1].tolist())
        temp = temp[:, :-1]
        if temp.size == 0: break


        spiral.extend(temp[-1, ::-1].tolist())
        temp = temp[:-1]
        if temp.size == 0: break


        spiral.extend(temp[::-1, 0].tolist())
        temp = temp[:, 1:]
    return spiral

print(numpy_boundry_traversal(arr))#spiral problem



[[36 50 41  8]
 [35 37 50 47]
 [20 16 50 34]
 [ 1 10 47 13]
 [43  5 46 28]]
50 50 50 47 46 
 [ 8 20 16  1 10 13  5 28]
[36, 50, 41, 8, 47, 34, 13, 28, 46, 5, 43, 1, 20, 35, 37, 50, 50, 47, 10, 16]


Problem 2

In [ ]:
import numpy as np
arr=np.random.uniform(0,10,size=20)
print(arr,'\n')
arr=arr.round(2)
print(arr,'\n')
print(f"Minimum: {arr.min()} Maximum: {arr.max() } Median: {np.median(arr)}",'\n')

replacer=arr<5
arr[replacer]=arr[replacer]**2

def numpy_alternate_sort(array):
  arr1=np.sort(array)
  arr2=arr1[::-1]
  arr=np.array([])
  for x in range(0,len(array)):
    if x%2==0:
      arr=np.append(arr,arr1[x])
    else:
      arr=np.append(arr,arr2[x])
  return arr

print(numpy_alternate_sort(arr))



[3.26222366 2.6729714  6.07012674 2.71028507 4.8793226  1.71669711
 6.41346945 8.8522607  3.14899054 3.55509775 5.58288873 6.07316959
 4.85751732 7.42185375 3.58202966 8.63555754 9.60287173 4.18414493
 9.27110941 7.23777876] 

[3.26 2.67 6.07 2.71 4.88 1.72 6.41 8.85 3.15 3.56 5.58 6.07 4.86 7.42
 3.58 8.64 9.6  4.18 9.27 7.24] 

Minimum: 1.72 Maximum: 9.6 Median: 5.23 

[ 2.9584 23.6196  6.07   12.8164  6.41   10.6276  7.24    9.6     7.42
  8.85    8.85    7.42    9.6     7.24   10.6276  6.41   12.8164  6.07
 23.6196  2.9584]


Problem 3

In [1]:
import pandas as pd
import numpy as np

subjects=["Maths","Physics","Chemistry","IP"]
sub=(np.random.choice(subjects,size=10)).tolist()
marks=(np.random.randint(0,101,size=10)).tolist()
data={"Name":["Ram1","Ram2","Ram3","Ram4","Ram5","Ram6","Ram7","Ram8","Ram9","Ram10"],"Subject":sub,"Marks":marks}

df=pd.DataFrame(data)

def assign(marks):
  if marks>=90:
    return "A"
  elif marks>=80:
    return "B"
  elif marks>=70:
    return "C"
  elif marks>=60:
    return "D"
  else:
    return "F"

df["Grade"]=df["Marks"].apply(assign)

print(df,'\n')
print(df.sort_values(by=["Marks"],ascending=False),'\n')
print(df.groupby("Subject")["Marks"].mean())

def pandas_filter_pass(dataframe):
  dataframe.drop("Marks",axis=1,inplace=True)
  dataframe.drop("Name",axis=1,inplace=True)
  dataframe.drop("Subject",axis=1,inplace=True)

  return dataframe

print(pandas_filter_pass(df))


    Name    Subject  Marks Grade
0   Ram1      Maths     97     A
1   Ram2    Physics     84     B
2   Ram3         IP     69     D
3   Ram4  Chemistry     16     F
4   Ram5  Chemistry     90     A
5   Ram6      Maths     58     F
6   Ram7      Maths     52     F
7   Ram8    Physics     18     F
8   Ram9    Physics     59     F
9  Ram10         IP     73     C 

    Name    Subject  Marks Grade
0   Ram1      Maths     97     A
4   Ram5  Chemistry     90     A
1   Ram2    Physics     84     B
9  Ram10         IP     73     C
2   Ram3         IP     69     D
8   Ram9    Physics     59     F
5   Ram6      Maths     58     F
6   Ram7      Maths     52     F
7   Ram8    Physics     18     F
3   Ram4  Chemistry     16     F 

Subject
Chemistry    53.000000
IP           71.000000
Maths        69.000000
Physics      53.666667
Name: Marks, dtype: float64
  Grade
0     A
1     B
2     D
3     F
4     A
5     F
6     F
7     F
8     F
9     C


Problem 4


In [21]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score



df=pd.read_csv("/content/drive/MyDrive/dataset/short_movies_reviews_sentiment.csv")

print(df)

vectorize=CountVectorizer(max_features=500,stop_words='english')
x=vectorize.fit_transform(df["review"])
y=df["sentiment"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=MultinomialNB()
model.fit(x_train,y_train)

acc=accuracy_score(y_test,y_predict)
print(acc)

def predict_review_sentiment(model,vectorizer,review):
  review_tokens=vectorizer.fit_transform([review])
  y=model.predict([review_tokens])
  return y






                                               review sentiment
0     The score is captivating and was unforgettable.  positive
1   The storytelling is engaging and was unforgett...  positive
2   The cinematography is impressive and left me w...  positive
3   The pacing is thought-provoking and stayed wit...  positive
4    The pacing is impressive and was a true delight.  positive
..                                                ...       ...
95  The soundtrack is lackluster and failed to eng...  negative
96  The pacing is lackluster and didn't leave an i...  negative
97   The cinematography is predictable and fell flat.  negative
98   The pacing is forgettable and felt like a chore.  negative
99  The visuals is forgettable and was a disappoin...  negative

[100 rows x 2 columns]
1.0


Problem 5

In [20]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder


df=pd.read_csv("/content/drive/MyDrive/dataset/short_text_dataset.csv")
#print(df)

x=df["text"]
y=df["label"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

le=LabelEncoder()
y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)

pipe=Pipeline([("Vectorizer",TfidfVectorizer(max_features=300,stop_words="english")),("Model",LogisticRegression())])
pipe.fit(x_train,y_train)
y_predict=pipe.predict(x_test)
print(df)

print(f1_score(y_test,y_predict))
print(precision_score(y_test,y_predict))
print(recall_score(y_test,y_predict))

def text_preprocess_vectorize(texts,vectorizer):
  return vectorizer.fit_transform([texts])


                                  text label
0               The plot is masterful.  good
1                The plot is touching.  good
2   The cinematography is predictable.   bad
3              The movie is fantastic.  good
4      The soundtrack is heartwarming.  good
..                                 ...   ...
95                 The acting is weak.   bad
96     The cinematography is mediocre.   bad
97             The movie is thrilling.  good
98              The movie is mediocre.   bad
99     The cinematography is touching.  good

[100 rows x 2 columns]
1.0
1.0
1.0
